controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: { p: 26000.0, i: 0, d: 600.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      joint2: { p: 30000, i: 0, d: 1000.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      joint3: { p: 24000.0, i: 0, d: 650.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      joint4: { p: 500.0, i: 10.0, d: 4., i_clamp_max: 60, i_clamp_min: -60.0, antiwindup: true, publish_state: true }
      joint5: { p: 50.0, i: 0, d: 0.6, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      joint6: { p: 280.0, i: 0, d: 3.5, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }


  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 2.0
      vel_coeff: 0.008
      power_offset: -9.8
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 4.0, i: 0, d: 0.02, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
    max_odom_vel: 10.0
    # OmniController
    wheels:
      left_front:
        pose: [ 0.227, 0.288, 0. ]
        roller_angle: -0.785
        joint: left_front_wheel_joint
        <<: &wheel_setting
          radius: 0.0684
          pid: { p: 0.4, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.227, -0.288, 0. ]
        roller_angle: 0.785
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.227, 0.288, 0. ]
        roller_angle: 0.785
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.227, -0.288, 0. ]
        roller_angle: -0.785
        joint: right_back_wheel_joint
        <<: *wheel_setting

  multi_dof_controller:
    type: multi_dof_controller/Controller
    position_tolerance: 1.0
    time_out: 10.0
    joints:
      pitch_front_joint:
        position:
          joint: pitch_front_joint
          pid: { p: 0.8, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
        velocity:
          joint: pitch_front_joint
          pid: { p: 0.02, i: 0., d: 0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
      pitch_behind_joint:
        position:
          joint: pitch_behind_joint
          pid: { p: 0.8, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
        velocity:
          joint: pitch_behind_joint
          pid: { p: 0.02, i: 0., d: 0., i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
      roll_left_joint:
        position:
          joint: roll_left_joint
          pid: { p: 0.7, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
        velocity:
          joint: roll_left_joint
          pid: { p: 0.02, i: 0., d: 0., i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
      roll_right_joint:
        position:
          joint: roll_right_joint
          pid: { p: 0.7, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
        velocity:
          joint: roll_right_joint
          pid: { p: 0.02, i: 0., d: 0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
    motions:
      angular_y:
        velocity: [ 1.5,1.5,-0.4,0.4 ]
        velocity_max_speed: 15
        position: [ 1.5,1.5,-0.2,0.2 ]
        position_per_step: 1
        fixed_direction: [ 0,0,1,1 ]
      angular_x:
        velocity: [ -0.5,0.5,1.3,1.3 ]
        velocity_max_speed: 15
        position: [ -0.5,0.5,0.5,0.5 ]
        fixed_direction: [ 1,1,0,0 ]
        position_per_step: 1
      linear_z:
        velocity: [ -0.6,0.6,1.0,-1.0 ]
        velocity_max_speed: 15
        position: [ -0.5,0.5,0.5,-0.5 ]
        fixed_direction: [ 0,0,0,0 ]
        position_per_step: 1
      linear_x:
        velocity: [ 0.,0.,1.0,-1.0 ]
        velocity_max_speed: 15
        position: [ -0.65,0.5,0.5,-0.5 ]
        fixed_direction: [ 0,0,0,0 ]
        position_per_step: 1



  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 2.0, i: 0.1, d: 0.05, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    pitch:
      joint: "pitch_joint"
      pid: { p: 0.5, i: 1.0, d: 0.012, i_clamp_max: 0.05, i_clamp_min: -0.05, antiwindup: true, publish_state: true }
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.0,0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 1.0
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.1
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

  gpio_controller:
    type: gpio_controller/Controller
    gpios: [ "gripper" ]

  joint1_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint1_motor ]
    velocity:
      search_velocity: 0.6
      vel_threshold: 0.001
      joint: joint1
      pid: { p: 220, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  joint2_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint2_motor ]
    velocity:
      search_velocity: 0.4
      vel_threshold: 0.001
      joint: joint2
      pid: { p: 300, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }

  joint3_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint3_motor ]
    velocity:
      search_velocity: -0.8
      vel_threshold: 0.001
      joint: joint3
      pid: { p: 45, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }

  joint4_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint4_motor ]
    velocity:
      search_velocity: -2.3
      vel_threshold: 0.05
      joint: joint4
      pid: { p: 10, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }

  joint5_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint5_motor ]
    velocity:
      search_velocity: -2.5
      vel_threshold: 0.001
      joint: joint5
      pid: { p: 1, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }

  joint6_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint6_motor ]
    velocity:
      search_velocity: -4.
      vel_threshold: 0.001
      joint: joint6
      pid: { p: 1., i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }
    return:
      joint: joint6
      pid: { p: 10, i: 0, d: 0.5, i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }
      target_position: 0.
    pos_threshold: 0.3

  pitch_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      search_velocity: -1.5
      vel_threshold: 0.01
      joint: pitch_joint
      pid: { p: 0.08, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }


  drag_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ drag_joint_motor ]
    velocity:
      search_velocity: -2.0
      vel_threshold: 0.05
      joint: drag_joint
      pid: { p: 0.87, i: 0, d: 0., i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }
  #    return:
  #      joint: drag_joint
  #      pid: { p: 0.87, i: 0.0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #      target_position: 1.7
  #    pos_threshold: 0.2

  mimic_drag_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ mimic_drag_joint_motor ]
    velocity:
      search_velocity: -2.0
      vel_threshold: 0.05
      joint: mimic_drag_joint
      pid: { p: 0.8, i: 0, d: 0., i_clamp_max: 0.0, i_clamp_min: 0, antiwindup: true }
  #    return:
  #      joint: mimic_drag_joint
  #      pid: { p: 0.87, i: 0.0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #      target_position: 1.7
  #    pos_threshold: 0.2

  drag_controller:
    type: effort_controllers/JointPositionController
    joint: drag_joint
    pid: { p: 30., i: 0., d: 1.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

  mimic_drag_controller:
    type: mimic_joint_controller/MimicJointController
    joint: mimic_drag_joint
    target_joint_name: drag_joint
    pid: { p: 30., i: 0., d: 1.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

  joint7_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: { p: 10., i: 0., d: 1.2, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  joint7_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ joint7_motor ]
    velocity:
      search_velocity: -2.0
      vel_threshold: 0.01
      joint: joint7
      pid: { p: 0.8, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }