can_motors:
  - can_id: 6
    can_bus: 1
    name: "pitch_joint_motor"
    type: "GM6020"
  - can_id: 3
    can_bus: 1
    name: "scope_joint_motor"
    type: "M2006"
    need_calibration: true
  - can_id: 4
    can_bus: 1
    name: "image_transmission_joint_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 4
    can_bus: 0
    name: "left_front_friction_wheel_joint_motor"
    type: "M3508"
  - can_id: 3
    can_bus: 0
    name: "right_front_friction_wheel_joint_motor"
    type: "M3508"
  - can_id: 2
    can_bus: 0
    name: "left_back_friction_wheel_joint_motor"
    type: "M3508"
  - can_id: 1
    can_bus: 0
    name: "right_back_friction_wheel_joint_motor"
    type: "M3508"
can_imus:
  - can_bus: 1
    name: "gimbal_imu"
    bias: [ -0.002333995, 0.003817375 ,-0.00196222 ]
dbus:
  - name: "dbus"
