rm_manual:
  robot_type: "standard"
  dbus_topic: "/rm_ecat_hw/dbus"
  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ "pitch_joint_motor" ]
  shooter_calibrate_motor: [ "cover_joint_motor", "trigger_joint_motor" ]
  chassis:
    topic: "/cmd_chassis"
    accel_x:
      - [ 50.0,99.0 ]
    accel_y:
      - [ 50.0,99.0 ]
    accel_z:
      - [ 50.0,99.0 ]
    safety_power: 50
    capacitor_threshold: 0.2
    charge_power: 20
    extra_power: 30
    burst_power: 220
    buffer_threshold: 10
    power_gain: 0.85
  vel:
    topic: "/cmd_vel"
    power_limit_topic: "/cmd_chassis"
    max_linear_x:
      - [ 50.0,2.1 ]
      - [ 80.0,2.8 ]
      - [ 100.0,3.2 ]
      - [ 220.0, 5.0 ]
    max_linear_y:
      - [ 50.0,2.1 ]
      - [ 80.0,2.8 ]
      - [ 100.0,3.2 ]
      - [ 220.0,5.0 ]
    max_angular_z:
      - [ 50.0,10.5 ]
      - [ 80.0,15.0 ]
      - [ 100.0,18.0 ]
      - [ 220.0,20.0 ]
    gyro_move_reduction: 0.85
    gyro_rotate_reduction: 0.6
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    gimbal_scale: 8.0
    track_timeout: 0.5
    finish_turning_threshold: 2.9
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/controllers/shooter_controller/command"
    track_armor_error_tolerance: 0.08
    track_buff_error_tolerance: 0.12
    target_acceleration_tolerance: 99.0
    speed_10m_per_speed: 10.0
    speed_15m_per_speed: 13.5
    speed_16m_per_speed: 16.0
    speed_18m_per_speed: 15.72
    speed_30m_per_speed: 27.2
    wheel_speed_15: 450.0
    wheel_speed_18: 500.0
    wheel_speed_30: 780.0
    extra_wheel_speed_once: 5.0
    heat_limit:
      low_shoot_frequency: 19
      high_shoot_frequency: 20
      burst_shoot_frequency: 20
      minimal_shoot_frequency: 1.75
      safe_shoot_frequency: 3
      safe_speed_limit: 30
      heat_coeff: 20.0
      is_local: true
      type: "ID1_17MM"
  camera:
    topic: "/camera_name"
    camera1_name: "hk_camera"
    camera2_name: "galaxy_camera"
  cover:
    topic: "/controllers/cover_controller/command"
    on_pos: 1.7
    off_pos: 0.0
  buff_switch:
    fail_limit: 10
    service_name: "/buff_status_switch"
  buff_type_switch:
    fail_limit: 10
    service_name: "/forecast/status_switch"
  detection_switch:
    fail_limit: 10
    service_name: "/Processor/status_switch"
  exposure_switch:
    fail_limit: 10
    service_name: "/exposure_status_switch"

  controllers_list:
    state_controllers:
      - controllers/joint_state_controller
      - controllers/robot_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/orientation_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
      - controllers/cover_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller
      - controllers/cover_calibration_controller
      - controllers/gimbal_calibration_controller

  gimbal_calibration:
    - start_controllers:
        - controllers/gimbal_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
      services_name:
        - /controllers/gimbal_calibration_controller/is_calibrated
    - start_controllers:
        - controllers/cover_calibration_controller
      stop_controllers:
        - controllers/cover_controller
      services_name:
        - /controllers/cover_calibration_controller/is_calibrated
  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/shooter_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated

controllers:
  cover_controller:
    type: effort_controllers/JointPositionController
    joint: "cover_joint"
    pid: { p: 5.0, i: 2.5, d: 0.5, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
